[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "8UiQyegaKKEoAnGg4UfSsgouz4n2qvhbT9PwouJx2d5s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/victorcarvalho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
